# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-27 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flatpages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('flatpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flatpages.FlatPage')),
                ('cartegoria', models.CharField(choices=[('Serviços', 'Serviços'), ('Institucional', 'Institucional'), ('Eventos', 'Eventos'), ('Livre', 'Livre')], max_length=15)),
                ('banner', models.ImageField(blank=True, upload_to='')),
            ],
            bases=('flatpages.flatpage',),
        ),
    ]
