# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-07 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('nome', models.CharField(max_length=100)),
                ('ra', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('ano_ingresso', models.DateField(null=True)),
                ('vinculo', models.CharField(choices=[('Graduacao', 'Graduacao'), ('Pós', 'Pós')], max_length=50, null=True)),
                ('email_pessoal', models.EmailField(max_length=254, null=True)),
                ('membro_confirmado', models.BooleanField(default=False)),
                ('token', models.CharField(max_length=37, null=True)),
                ('token_auxiliar_confirmado', models.BooleanField(default=False)),
            ],
        ),
    ]
