# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-30 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('nome', models.CharField(max_length=100)),
                ('ra', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('token', models.CharField(max_length=37)),
                ('confirmado', models.BooleanField(default=False)),
                ('email_pessoal', models.EmailField(max_length=254)),
                ('nascimento', models.DateField()),
                ('cpf', models.CharField(max_length=20)),
                ('vinculo', models.CharField(choices=[('Graduacao', 'Graduacao'), ('Pós', 'Pós')], max_length=50)),
            ],
        ),
    ]
