# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-28 18:46
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
