# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-27 13:55
from __future__ import unicode_literals

import banco_de_provas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prova',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=banco_de_provas.models.nomedoarquivo)),
                ('materia', models.CharField(max_length=10)),
                ('semestre', models.CharField(max_length=10)),
                ('professor', models.CharField(blank=True, max_length=50)),
                ('tipo', models.CharField(max_length=15)),
                ('aprovado', models.BooleanField(default=True)),
            ],
        ),
    ]
