# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 21:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitecaco', '0016_auto_20150330_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='noticia',
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
