# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-27 19:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitecaco', '0017_auto_20160416_1845'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ata',
        ),
        migrations.DeleteModel(
            name='InscricaoFISL',
        ),
        migrations.DeleteModel(
            name='Livro',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pagina',
            name='flatpage_ptr',
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
        migrations.DeleteModel(
            name='Prova',
        ),
        migrations.DeleteModel(
            name='Noticia',
        ),
        migrations.DeleteModel(
            name='Pagina',
        ),
    ]
