# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-31 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecaco', '0018_auto_20161227_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivo',
            name='descricao',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='arquivo',
            name='nome',
            field=models.CharField(default='Arquivo', max_length=100),
        ),
        migrations.AddField(
            model_name='arquivo',
            name='tipo',
            field=models.CharField(choices=[('BannerAtivo', 'BannerAtivo'), ('BanneInativo', 'BanneInativo'), ('ImagensGeral', 'ImagensGeral'), ('Outros', 'Outros')], default='Outros', max_length=30),
        ),
    ]
