# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-27 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InscricaoFISL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('sexo', models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=150)),
                ('RA', models.CharField(max_length=10, null=True)),
                ('nascimento', models.DateField()),
                ('cidade', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=20)),
                ('RG', models.CharField(max_length=20)),
                ('Orgao_expedidor', models.CharField(max_length=20)),
                ('telefone', models.CharField(max_length=30)),
                ('vinculo', models.CharField(choices=[('Computeiro', 'Aluno Computação Unicamp'), ('Unicamper não Computeiro', 'Aluno Unicamp'), ('Brother X', 'Nenhum/Outro')], max_length=50)),
            ],
        ),
    ]
