# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-27 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('autor', models.CharField(max_length=150)),
                ('edicao', models.CharField(max_length=3)),
                ('observacao', models.CharField(blank=True, max_length=200)),
                ('disponivel', models.BooleanField(default=True)),
            ],
        ),
    ]
